In [1]:
from model import *
from data import *

C:\SoftWare\Anaconda2\envs\python3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


## Train your Unet with membrane data
membrane data is in folder membrane/, it is a binary classification task.

The input shape of image and mask are the same :(batch_size,rows,cols,channel = 1)

### Train with data generator

In [2]:
data_gen_args = dict(rotation_range=0.2,
                    width_shift_range=0.05,
                    height_shift_range=0.05,
                    shear_range=0.05,
                    zoom_range=0.05,
                    horizontal_flip=True,
                    fill_mode='nearest')
myGene = trainGenerator(2,'data/membrane/train','image','label',data_gen_args,save_to_dir = None)
model = unet()
model_checkpoint = ModelCheckpoint('unet_membrane.hdf5', monitor='loss',verbose=1, save_best_only=True)
model.fit_generator(myGene,steps_per_epoch=2000,epochs=5,callbacks=[model_checkpoint])

C:\Users\xuhaozhi\Documents\Study\unet\model.py:34: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  merge6 = merge([drop4,up6], mode = 'concat', concat_axis = 3)
C:\SoftWare\Anaconda2\envs\python3\lib\site-packages\keras\legacy\layers.py:465: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)
C:\Users\xuhaozhi\Documents\Study\unet\model.py:39: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  merge7 = merge([conv3,up7], mode = 'concat', concat_axis = 3)
C:\Users\xuhaozhi\Documents\Study\unet\model.py:44: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `

Epoch 1/5
Found 30 images belonging to 1 classes.
Found 30 images belonging to 1 classes.
2000/2000 [==============================] - 538s 269ms/step - loss: 0.1951 - acc: 0.9140

Epoch 00001: loss improved from inf to 0.19511, saving model to unet_membrane.hdf5
Epoch 2/5
2000/2000 [==============================] - 535s 268ms/step - loss: 0.1210 - acc: 0.9469

Epoch 00002: loss improved from 0.19511 to 0.12099, saving model to unet_membrane.hdf5
Epoch 3/5
2000/2000 [==============================] - 534s 267ms/step - loss: 0.0926 - acc: 0.9596

Epoch 00003: loss improved from 0.12099 to 0.09256, saving model to unet_membrane.hdf5
Epoch 4/5
2000/2000 [==============================] - 534s 267ms/step - loss: 0.0788 - acc: 0.9656

Epoch 00004: loss improved from 0.09256 to 0.07882, saving model to unet_membrane.hdf5
Epoch 5/5
2000/2000 [==============================] - 534s 267ms/step - loss: 0.0707 - acc: 0.9691

Epoch 00005: loss improved from 0.07882 to 0.07074, saving model to une

### Train with npy file

In [ ]:
#imgs_train,imgs_mask_train = geneTrainNpy("data/membrane/train/aug/","data/membrane/train/aug/")
#model.fit(imgs_train, imgs_mask_train, batch_size=2, nb_epoch=10, verbose=1,validation_split=0.2, shuffle=True, callbacks=[model_checkpoint])

### test your model and save predicted results

In [3]:
testGene = testGenerator("data/membrane/test")
model = unet()
model.load_weights("unet_membrane.hdf5")
results = model.predict_generator(testGene,30,verbose=1)
saveResult("data/membrane/test",results)

C:\Users\xuhaozhi\Documents\Study\unet\model.py:34: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  merge6 = merge([drop4,up6], mode = 'concat', concat_axis = 3)
C:\SoftWare\Anaconda2\envs\python3\lib\site-packages\keras\legacy\layers.py:465: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)
C:\Users\xuhaozhi\Documents\Study\unet\model.py:39: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  merge7 = merge([conv3,up7], mode = 'concat', concat_axis = 3)
C:\Users\xuhaozhi\Documents\Study\unet\model.py:44: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `

 1/30 [>.............................] - ETA: 4s

C:\SoftWare\Anaconda2\envs\python3\lib\site-packages\skimage\transform\_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
C:\SoftWare\Anaconda2\envs\python3\lib\site-packages\skimage\transform\_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "


30/30 [==============================] - 1s 47ms/step


C:\SoftWare\Anaconda2\envs\python3\lib\site-packages\skimage\util\dtype.py:130: UserWarning: Possible precision loss when converting from float32 to uint16
  .format(dtypeobj_in, dtypeobj_out))


In [1]:
import numpy as np

In [2]:
train = np.load('./data/npydata/imgs_train.npy')

In [3]:
train.shape

(100, 400, 400, 3)

In [6]:
labels = np.load('./data/npydata/imgs_mask_train.npy')

In [5]:
labels.shape

(100, 400, 400, 1)

In [7]:
test = np.load('./data/npydata/imgs_test.npy')

In [8]:
test.shape

(50, 608, 608, 3)

In [10]:
print(train[:3,:3,:3,:])

[[[[ 98  89  81]
   [ 70  63  55]
   [ 64  60  51]]

  [[ 72  64  55]
   [ 68  59  51]
   [ 70  62  54]]

  [[104  95  87]
   [ 94  85  76]
   [ 95  86  77]]]


 [[[ 85  85  66]
   [ 29  44  20]
   [ 46  64  41]]

  [[127 124 109]
   [ 47  57  38]
   [ 35  53  31]]

  [[ 58  59  49]
   [ 46  53  40]
   [ 41  56  37]]]


 [[[ 69  66  60]
   [ 76  74  68]
   [ 76  72  70]]

  [[ 71  69  63]
   [ 77  73  69]
   [ 74  70  69]]

  [[ 75  71  67]
   [ 75  71  70]
   [ 74  71  72]]]]


In [11]:
print(labels[:3,:3,:3,:])

[[[[  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]]]


 [[[  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]]]


 [[[237]
   [237]
   [237]]

  [[237]
   [237]
   [237]]

  [[237]
   [237]
   [237]]]]


In [12]:
print(labels[labels != 0])

[  4 117 237 ...   1   2   1]


In [13]:
test = np.array(["abc", "Julien"])

In [15]:
names = np.load('./data/npydata/imgs_train_names.npy')

In [18]:
names

array(['satImage_063.png', 'satImage_013.png', 'satImage_099.png',
       'satImage_023.png', 'satImage_034.png', 'satImage_100.png',
       'satImage_078.png', 'satImage_001.png', 'satImage_030.png',
       'satImage_026.png', 'satImage_070.png', 'satImage_076.png',
       'satImage_098.png', 'satImage_060.png', 'satImage_086.png',
       'satImage_088.png', 'satImage_038.png', 'satImage_073.png',
       'satImage_055.png', 'satImage_031.png', 'satImage_037.png',
       'satImage_047.png', 'satImage_059.png', 'satImage_082.png',
       'satImage_084.png', 'satImage_027.png', 'satImage_058.png',
       'satImage_006.png', 'satImage_071.png', 'satImage_014.png',
       'satImage_074.png', 'satImage_041.png', 'satImage_011.png',
       'satImage_035.png', 'satImage_042.png', 'satImage_002.png',
       'satImage_039.png', 'satImage_064.png', 'satImage_091.png',
       'satImage_020.png', 'satImage_096.png', 'satImage_072.png',
       'satImage_019.png', 'satImage_065.png', 'satImage_083.p