In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [77]:
from proj1_helpers import *
from implementations import *

In [3]:
train_data = 'all/train.csv'

In [95]:
yb, input_data, ids, features = load_csv_data(train_data)

In [96]:
N = yb.size
undefined_ratio = []
for i, feature_name in enumerate(features[2:]):
    feature_column = input_data[:,i]
    defined_indices = feature_column == -999
    # cleaned_data = yb[defined_indices]
    undefined_ratio.append(defined_indices.sum() / N)

In [97]:
undefined_ratio = np.array(undefined_ratio)

In [98]:
clean_features = undefined_ratio < 0.7

In [102]:
clean_features.sum

<function ndarray.sum>

In [99]:
better_features = input_data[:,clean_features]

IndexError: boolean index did not match indexed array along dimension 1; dimension is 30 but corresponding boolean dimension is 28

In [22]:
x, mean_x, std_x = standardize(input_data)
tx = build_model_data(x)

In [42]:
y_tr.shape

(225000, 31)

In [43]:
x_tr, x_te, y_tr, y_te = split_data(tx, yb, 0.9)

In [86]:
initial_w = np.zeros(tx.shape[1])
max_iter = 100000
gamma = 0.01

In [87]:
tx[0]

array([1.        , 0.72343805, 0.52317289, 0.62968263, 0.46855931,
       0.40611413, 0.69169874, 0.41016488, 0.41108299, 0.50073461,
       0.86020844, 0.4076643 , 0.40723524, 0.4044763 , 0.4793044 ,
       0.40636096, 0.40489383, 0.52310599, 0.40925831, 0.39844632,
       0.44282461, 0.40337596, 1.00086119, 0.40862855, 0.55957425,
       0.40897457, 0.40503916, 0.51027093, 0.40687538, 0.3983056 ,
       0.66583024])

In [88]:
losses, ws = least_squares_GD(y_tr, x_tr, initial_w, max_iters, gamma)

In [89]:
w_logistic = ws[-1]

In [90]:
w_logistic

array([-0.03393437,  0.11420982, -0.03937447, -0.02146278, -0.00755878,
        0.00643361,  0.05894637,  0.00564976, -0.01379751, -0.01818839,
       -0.02176061, -0.01419345, -0.01326495,  0.0062806 , -0.0072529 ,
       -0.01371324, -0.01372963, -0.02057526, -0.01371006, -0.01369353,
       -0.0182539 , -0.01369213, -0.02764377, -0.01388593,  0.02154312,
        0.02040222,  0.02040284,  0.00239982,  0.00623481,  0.00622122,
       -0.02135244])

In [91]:
error(y_te,x_te,w_logistic)

0.31628

In [92]:
w_least_squares= least_squares(y_tr,x_tr)

In [93]:
w_least_squares

array([-1.58394721e+03,  3.14982752e-02, -3.08150109e+00, -2.70865061e+00,
       -1.94193219e-01, -1.29750491e+00,  1.98430150e-01, -1.00911037e+01,
        1.48874777e+02, -5.64222162e-02, -1.95498913e+03, -9.42503330e+01,
        4.16451918e+01,  1.95109351e+01,  1.95868326e+03, -1.63600388e-02,
       -6.23081084e-01,  1.96062555e+03,  5.22693931e-02,  4.39690044e-01,
        1.58149605e+00, -2.27043733e-01, -2.16882810e-01, -9.08913101e+01,
       -1.08770265e-01,  5.47342542e-03,  2.42997502e-01, -5.02841061e-02,
       -2.63806866e+00, -5.51536390e+00,  1.95467579e+03])

In [94]:
error(y_te,x_te,w_least_squares)

0.25588